name: Code checks - Copyright

on: [push]

jobs:
  copyright_check:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Liscence check
        run: python buildbot/check_licencing.py
