name: DPCPP linux pipeline

on:
    workflow_call:
        inputs:
            clang:
                required: true
                type: string
            os:
                required: true
                type: string
            cuda:
                required: true
                type: string
            rocm:
                required: true
                type: string
      
jobs:
    # download and cache dpcpp compiler
    cache_dpcpp:
        uses: ./.github/workflows/linux-cache-dpcpp.yml
        with:
            clang: ${{ inputs.clang }}
            os: ${{ inputs.os }}
            cuda: ${{ inputs.cuda }}
            rocm: ${{ inputs.rocm }}
  
    shamrock_dpcpp:
        needs: cache_dpcpp
        uses: ./.github/workflows/shamtest-dpcpp.yml
        with:
            clang: ${{ inputs.clang }}
            os: ${{ inputs.os }}
            cuda: ${{ inputs.cuda }}
            rocm: ${{ inputs.rocm }}
