name: OpenSYCL linux pipeline

on:
    workflow_call:
        inputs:
          clang:
                required: true
                type: string
          os:
                required: true
                type: string
          cuda:
                required: true
                type: string
          rocm:
                required: true
                type: string
      
jobs:
    
    cache_opensycl:
        uses: ./.github/workflows/linux-cache-opensycl.yml
        with:
            clang: ${{ inputs.clang }}
            os: ${{ inputs.os }}
            cuda: ${{ inputs.cuda }}
            rocm: ${{ inputs.rocm }}
        secrets: inherit

    shamrock_test_opensycl:
        needs: cache_opensycl
        uses: ./.github/workflows/shamtest-opensycl.yml
        with:
            clang: ${{ inputs.clang }}
            os: ${{ inputs.os }}
            cuda: ${{ inputs.cuda }}
            rocm: ${{ inputs.rocm }}
        secrets: inherit