name: Build Dpcpp

on: [push]

jobs:
  copyright_check:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name : Download DPCPP
        run: |
          wget -q --show-progress --progress=bar:force:noscroll https://github.com/intel/llvm/releases/download/sycl-nightly%2F20230112/dpcpp-compiler.tar.gz -O dpcpp-compiler.tar.gz
      
      - name : Untar
        run: |
          echo "untar : "
          tar -xf dpcpp-compiler.tar.gz
          echo "rm archive"
          rm dpcpp-compiler.tar.gz
          
      - name : Check binary
        run: |
          dpcpp_compiler/bin/clang++ --version
      
