name: Build OpenSycl - Ubuntu

on: [push]

jobs:
  build_opensycl:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: clone OpenSycl
        run: git clone --recurse-submodules https://github.com/OpenSYCL/OpenSYCL.git

      - name: install boost
        run: sudo apt install libboost-all-dev

      - name: install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15
          sudo apt install libclang-15-dev clang-tools-15 libomp-15-dev

      - name: install Ninja-build
        run: sudo apt install ninja-build

      - name: configure OpenSycl
        run: |
          cd OpenSYCL
          cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++-15 -DCLANG_EXECUTABLE_PATH=/usr/bin/clang++-15 -DLLVM_DIR=/usr/lib/llvm-15/cmake -DCMAKE_INSTALL_PREFIX=../OpenSYCL_comp .
          make -j install

      - name: configure Shamrock
        run: |
          python3 buildbot/configure.py --gen ninja --tests --build debug \
            --outdir opensycl_omp_debug --cxxpath OpenSYCL_comp --compiler opensycl --profile omp

      - name: compile Shamrock
        run: |
          cd opensycl_omp_debug
          ninja

      - name: run Shamrock Unittests
        run: |
          cd opensycl_omp_debug
          ./shamrock_test --sycl-cfg 0:0 --loglevel 0 --unittest

      
