name: Build OpenSycl

on: [push]

jobs:
  copyright_check:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: clone OpenSycl
        run: git clone --recurse-submodules https://github.com/OpenSYCL/OpenSYCL.git

      

      - name: configure OpenSycl
        run: |
          cd OpenSYCL
          cmake -DCMAKE_INSTALL_PREFIX=../OpenSYCL_comp .
          make -j install
