name: shamtest DPCPP


on:
  workflow_call:
    
jobs:
  shamrock_dpcpp:

    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name : Install pck (DPCPP)
        run: |
          sudo apt-get install -y -qq g++-10 clang libomp-dev libtinfo5 libopenmpi-dev openmpi-bin openmpi-common
          
      - name: install Ninja-build
        run: sudo apt install ninja-build

      - name: Cache DPCPP
        id: cache-dpcpp
        uses: actions/cache@v3
        with:
          path: dpcpp_compiler
          key: sycl-nightly%2F20230112_dpcpp-compiler.tar.gz
          
      - name : Check binary
        run: |
          dpcpp_compiler/bin/clang++ --version

      
      - name: configure Shamrock
        run: |
          python3 buildbot/configure.py --gen ninja --tests --build debug \
            --outdir dpcpp_bare_debug --cxxpath dpcpp_compiler --compiler dpcpp --profile bare

      - name: compile Shamrock
        run: |
          cd dpcpp_bare_debug
          ninja