name: Acpp/clang15


on:
  workflow_call:


jobs:


  shamrock_acpp:
    name: AdaptiveCpp omp clang-${{ matrix.clang }}
    runs-on: [self-hosted, ubuntu20]

    strategy:
      matrix:
        clang: [15]
        cuda: [11.0.2]
        rocm: [5.4.3]
        profile: [omp, generic, cuda-sm70, hip-gfx906]
    #if: false
  
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
  
      - name: ls local
        run : ls -la
  
      - name: configure Shamrock
        run: |
          python3 buildbot/configure.py --gen ninja --tests --build release \
            --builddir build --cxxpath /home/docker/compilers/AdaptiveCpp_clang${{matrix.clang}} --compiler acpp --profile ${{ matrix.profiles }}
  
      - name: compile Shamrock
        run: |
          cd build
          ninja
  
      - name: run Shamrock Unittests world_size = 1
        run: |
          cd build
          ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
  
      - name: run Shamrock Unittests world_size = 2
        run: |
          cd build
          mpirun -n 2 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
      
      - name: run Shamrock Unittests world_size = 3
        run: |
          cd build
          mpirun --oversubscribe -n 3 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
  
      - name: run Shamrock Unittests world_size = 4
        run: |
          cd build
          mpirun --oversubscribe -n 4 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi




  shamrock_acpp_cuda_nvcxx:
    name: AdaptiveCpp nvcxx ${{matrix.nvhpc}}, CUDA ${{matrix.cuda}}
    runs-on: [self-hosted, ubuntu20]

    strategy:
      matrix:
        nvhpc: [22.11]
        cuda: [11.8]

    if: false
  
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
  
      - name: ls local
        run : ls -la
  
      - name: configure Shamrock
        run: |
          python3 buildbot/configure.py --gen ninja --tests --build release \
            --builddir build --cxxpath /home/docker/compilers/AdaptiveCpp_clang${{matrix.clang}} --compiler acpp --profile cuda-nvcxx
  
      - name: compile Shamrock
        run: |
          cd build
          ninja
  
      - name: run Shamrock Unittests world_size = 1
        run: |
          cd build
          ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
  
      - name: run Shamrock Unittests world_size = 2
        run: |
          cd build
          mpirun -n 2 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
      
      - name: run Shamrock Unittests world_size = 3
        run: |
          cd build
          mpirun --oversubscribe -n 3 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
  
      - name: run Shamrock Unittests world_size = 4
        run: |
          cd build
          mpirun --oversubscribe -n 4 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
